### PR TITLE
Fix096presets

### PR DESCRIPTION
**Pull request by CoMPaTech**
Accompanying https://github.com/laetificat/haanna/pull/6 with the requests from #13 to a PR.

> **NOTICE**
> 
> In readying (before the infamous `climate-1.0` change in HA) this component for upstreaming to the HA project we should rename it to vendor logic. As Plugwise selss more than just climate and we have some community members looking for inc
> lusion of Adam's and Lisa's, changing the name accordingly. For now you can leave your `custom_components/anna` where it is - just create `custom_conponents/plugwise` and modify your `configuration.yaml` to state `platform: plugwise` (ins
> tead of 'platform: anna'

This should be tested on other devices as well, this is not for the faint (or unexperienced) of heart as you'll have to modify your `haanna.py` file (stashed in your python library) or until 0.10 is release (see above PR mentioned). Afterwards follow above notice with regards to the renaming.

Thanks to @bouwew for bringing the fire - we have progress, but there should be a couple of commits still coming to this PR before it's ready. Hang in there, schedule-wanters :)

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Crosslink progress screenshots: https://community.home-assistant.io/t/advice-how-to-load-sensor-info-from-plugwise-anna-thermostat-web-interface-xml/87801/102?u=compatech

**Comment by bouwew** [comment]
Hi Tom,

I've managed to set up both haanna 0.10.0 and the new plugwise component on a HA-test system.
I can reproduce the functions that you show in the Community thread. More testing during the weekend!

**Comment by CoMPaTech** [comment]
Looking forward to results!

**Comment by CoMPaTech** [comment]
Testing looks good - waiting for @laetificat to either upload haanna 0.10 to PyPi or allow me to collaborate on that. PRs for HA are also in-progress.

Unable to merge until 0.10 hits PyPi

**Pull request merged**
