### PR TITLE
Line up anna-ha dev code with HAC official code

### PR DESCRIPTION
**Pull request by bouwew**
For details, see here: https://github.com/home-assistant/home-assistant/pull/31209

### CODE REVIEW

**Comment by bouwew** [comment]
@CoMPaTech can you please also pull this one in?
This is exactly the same code as in HAC official, except for the name.

**Comment by CoMPaTech** [comment]
Sure, but should we leave this at .1 or also bump that to .2? (Just asking before merging)

**Comment by bouwew** [comment]
You're right, I'll fix that now.

**Comment by CoMPaTech** [comment]
Let's merge it up :)

**Comment by bouwew** [comment]
Thanks!

**Pull request merged**
