### PR TITLE
Updated Plugwise/anna-ha component matching the changes in haanna 0.11.0

### PR DESCRIPTION
**Pull request by bouwew**
- Can now show the domestic_hot_water status ("dhw" as hvac_action-text)  (tested)
- Can now show the cooling status. Supports also combined heating-cooling (tested)
- Automatic detection of available functions (only heating or cooling and heating combined) based on the presence of the determining parameters in the Anna XML-data. Will now display the various states via the preset-name, see also the closed pull-request #21.

### CODE REVIEW

**Comment by bouwew** [comment]
I'm closing this one for now.
I'm trying to find out how the combined heat_cool function is supposed to work.
Apparently the only use-case is an Elga heat-pump in combination with a gas cv-heater.
And, stand-alone cooling is not supported by the Anna, I think.

**Comment by bouwew** [comment]
Made some fixes:
- removed the cooling-only option, not supported on the Anna
- fixes in the logic

**Comment by bouwew** [comment]
Also tested by marcelveldt on a system with cooling (gas-heater + Elga heatpump).

**Comment by bouwew** [comment]
@CoMPaTech please merge this pull-request?

**Comment by CoMPaTech** [comment]
I didn't test it yet, but as we are in dev, I'll merge it right away :)

**Comment by bouwew** [comment]
Great, thanks!
Tested by marcelveldt (heat_cool) and me. Not sure how "deep" the cooling bit was tested. But he did not report any strange issues

**Pull request merged**
