### PR TITLE
Updated readme typo and re-added presets

### LINKED ISSUE #12: Not all attributes are shown
Hi, I think there are several bugs in Anna, possibly in Haanna? The active preset is not shown in the attributes of the climate-entity in HA, on version 0.96.1. When I read through the code, there is a bit of code covering that.

I switched to my test-VM which is still on 0.94, the climate.anna_thermostat shows the following attributes:
```
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
hold_mode: asleep
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 257
```

On 0.96.1, these are shown:
```
hvac_modes: heat,auto,off
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 1
```

When looking through the code, both old and new, some attributes seem to be missing, on 0.96.1: current preset mode, hvac mode, and outdoor temperature.

Could it be that these have the status None? And the status of these attributes is not updated due to a bug in the (haanna?) code? I noticed that when the status of an attribute is None, the attribute is not shown in HA.

### PR DESCRIPTION
**Pull request by CoMPaTech**
This should fix #12 @bouwew 

```
hvac_modes: heat,auto,off
current_temperature: 24.3
min_temp: 4
max_temp: 30
temperature: 20
hvac_action: idle
preset_mode: home
preset_modes: home,vacation,no_frost,asleep,away
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 17
```

Do note that this still doesn't make the schedule thing work, more work is required on that (and hass will just report 'can't call service'.
Giving it a test run (changing on app or browser directly to the `smile` updates `preset_mode` when updates are fetched. Pushing the temperature to 27 make `hvac_action` go into `heating` (after update) and after another update the device state moves from `idle` to `heating` as well.

### CODE REVIEW

**Comment by bouwew** [comment]
@CoMPaTech 
Hi Tom, confirmed, working, I see the same attributes as shown above.
But the outdoor_temperature attribute is still missing, I think?

Question: isn't this double code?
```
    @property
    def current_preset_mode(self):
        """Return the current preset mode, e.g., home, away, temp."""
        return self._preset_mode

    @property
    def preset_mode(self):
        """Return the current preset mode, e.g., home, away, temp."""
        return self._preset_mode
```

**Comment by bouwew** [comment]
Also, isn't this double code?

```
    @property
    def preset_mode(self):
        """Polling is needed"""
        return self._preset_mode

    @property
    def preset_modes(self):
        """Polling is needed"""
        return ATTR_PRESET_MODES

    def update(self):
        """Update the data from the thermostat"""
        ...

    @property
    def name(self):
        ...

    @property
    def current_preset_mode(self):
        """Return the current preset mode, e.g., home, away, temp."""
        ...

    @property
    def preset_mode(self):
        """Return the current preset mode, e.g., home, away, temp."""
        return self._preset_mode

    @property
    def preset_modes(self):
        """Return the vailable preset modes, e.g., home, away, temp."""
        return ATTR_PRESET_MODES
```
def preset_mode(self) and def preset_modes(self) are declared two times?

Please excuse me when I'm wrong, I'm just getting the hang of Python programming :)

**Comment by bouwew** [comment]
I removed the parts that I think are double and the component is still working.

Also, something else: you have defined the parameter hvac_action with the states heating and idle.
I'm thinking, this means that you are replacing the hvac_modes parameter. You are moving away from the HA defaults.  Wouldn't it be better to stick to using the hvac_modes parameter? Its modes heat and off are basically the same as the modes heat and idle of the hvac_action parameter? And, thinking of the future, the hvac_mode auto could be used to represent that a weekly schematic is active - update - after some thought, maybe that is not a good idea.

**Comment by CoMPaTech** [comment]
Trying to copy to hard between development and testing machines, you caught me red-handed :)
I'm currently reworking my 'in-progress' for upstream so at least our code in this repo is ready for upstreaming. Next commit to #14 will be PEP8 style correct and according to HA guidelines.

I currently opted to reuse the HVAC settings and just have heating/idle in there to make sure the component works as intended (with schema's/schedules still out to wrap our minds around how to incoporate). Looking at [climate init](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/__init__.py) though they have schedule stuff already in there. In terms of HVAC our dear Anna (or any plugwise relative) can only do heat or be idle if you make the comparison on [climate const](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/const.py) but I still need to grasp how that really works :) I'll review [developers climate](https://developers.home-assistant.io/docs/en/entity_climate.html) as well later today.

Last but not least learned how to incorporate custom attributes, hence `outdoor_temperature` is there again :)

**Comment by bouwew** [comment]
Great! The 2nd update works nicely, with the outdoor temp being shown :)

**Comment by bouwew** [comment]
I noticed that the Operation-choices Heat, Auto and Idle do nothing. These are general states the user can use to control the heating/cooling manually, I guess? I think we don't want these? The Anna does not support manual control other than via the temperature-setting. Maybe remove the related attributes?

**Comment by bouwew** [comment]
Never mind, I tried to remove these general states, but HA complains about missing hvac_modes. I guess these are mandatory.

**Comment by CoMPaTech** [comment]
If I remove those we loose heating/idle as well (or I think I ran into that during testing). So indeed they return 'not implemented'. I figured the same you do - we could just push _current_temperature + 1.5 degrees to have heating on. I'll ask on discord :)

**Comment by bouwew** [comment]
I'm thinking, for Anna, the only applicable hvac_mode is auto. It is supposed to be always on and the operation is automatic.
Heat and off would mean that the Anna-thermostat is overridden and that the heating-device is to be controlled directly, basically bypassing the Anna-control functions. I don't think the Anna-software allows any manual heating on/off-control?
Anyway, it is clear to me know why the hvac_modes have to be there: the climate platform requires it. Oh well :)

**Comment by CoMPaTech** [comment]
:)
I'd rather see 'heating and idling' with additional 'auto' (meaning *a* schedule is active). Which schedule is than up for debate. Although (but I'll mark this down in the other issue as well, we can just use custom attributes to get parts of the schema-thing.

**Pull request merged**
