### PR TITLE
Updates to conform to climate-1.0 in hass 0.96

### PR DESCRIPTION
**Pull request by CoMPaTech**
Conforming to https://github.com/home-assistant/home-assistant/pull/23899

### CODE REVIEW

**Comment by CoMPaTech** [comment]
"Works on my Anna" 👍 
If someone can test it as well I'm happy to push the merge button!

**Comment by bouwew** [comment]
Hi Tom, I just copied over your updated code after the upgrade of HA to 0.96.0. It seems to work.
A question though, when I open the device on the States-page, under Operation there are 3 states: Heat, Auto and Off. Only Off-mode seems to work. The other 2 result in a failed-message popping up on the screen. Is it supposed to "work" like this at the moment?

**Comment by CoMPaTech** [comment]
In all fairness I didn't check this morning if they 'controlled' the device, but setting my temperature to 25 did give the 'flare' in the plugwise app on my phone and after a minute also set the "Heat" to on in that box :)

So at least for status it works.

**Comment by CoMPaTech** [comment]
(no it doesn't work, the set_hvac_mode doesn't apply - I'll have to look into it, not even sure if we actually can 'force' it to heat ... it only does that based on temperature I recon)

**Comment by bouwew** [comment]
Ok, clear. Thanks for checking :)

**Comment by CoMPaTech** [comment]
Added note in the readme, merging!

**Comment by bouwew** [comment]
Text moved into an Issue.

**Comment by bouwew** [comment]
Old:
```
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
hold_mode: asleep
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 257
```

On 0.96.1:
```
hvac_modes: heat,auto,off
current_temperature: 22.8
min_temp: 4
max_temp: 30
temperature: 19.5
friendly_name: Anna Thermostat
icon: mdi:thermometer
supported_features: 1
```

**Pull request merged**
